// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pidxmdvrqjxwgaaoxecb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBpZHhtZHZycWp4d2dhYW94ZWNiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY3ODIzMzAsImV4cCI6MjA2MjM1ODMzMH0.xNyLnqBJ2c4KKN-J8uhNZNeBbS4RZhY69V9xr9myhxw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);